services:
  - type: web
    name: media-scrape-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT app:app
    autoDeploy: true
    plan: starter
    envVars:
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        value: app7iv7XirA2VzppE
      - key: AIRTABLE_TABLE_NAME
        value: Videos & Images
      - key: SHORTCUTS_KEY        # <-- rename to this
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
