name: Keep Render Backend Warm

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    concurrency:
      group: keepalive
      cancel-in-progress: true
    steps:
      - name: Wake /health
        run: |
          curl -fsS -m 20 -A "keepalive-gha" \
            https://media-scrape-backend.onrender.com/health \
            || echo "Ping failed (cold start or transient) — will retry in 5m"
